from .categoria_listar import CategoriaListView
from .categoria_crear import CategoriaCreateView
from .categoria_editar import CategoriaUpdateView
from .categoria_eliminar import CategoriaDeleteView
from .dato_listar import DatoListView
from .dato_crear import DatoCreateView
from .dato_editar import DatoUpdateView
from .dato_eliminar import DatoDeleteView
from .valor_listar import ValorListView
from .valor_crear import ValorCreateView
from .valor_editar import ValorUpdateView
from .valor_eliminar import ValorDeleteView
